require("dotenv").config();
const express = require("express");
const cors = require("cors");
const patientRoutes = require("./routes/patientRoutes");
const visitRoutes = require("./routes/visitRoutes");
const medicineRoutes = require("./routes/medicineRoutes");
const dashboardRoutes = require("./routes/dashboardRoutes");
const appointmentRoutes = require("./routes/appointmentRoutes");
const clinicSettingsRoutes = require("./routes/clinicSettingsRoutes");
const serviceRoutes = require("./routes/serviceRoutes");
const invoiceRoutes = require("./routes/invoiceRoutes");
const ipdRoutes = require("./routes/ipdRoutes");
const { metricsHandler, metricsMiddleware } = require("./monitoring/metrics");
const { notFound, errorHandler } = require("./middleware/errorMiddleware");
const app = express();
app.use(cors());
app.use(express.json());
app.use(metricsMiddleware);
app.get("/metrics", metricsHandler);
app.use("/api/patients", patientRoutes);
app.use("/api/visits", visitRoutes);
app.use("/api/medicines", medicineRoutes);
app.use("/api/dashboard", dashboardRoutes);
app.use("/api/appointments", appointmentRoutes);
app.use("/api/clinic-settings", clinicSettingsRoutes);
app.use("/api/services", serviceRoutes);
app.use("/api/invoices", invoiceRoutes);
app.use("/api/ipd", ipdRoutes);
app.use(notFound);
app.use(errorHandler);
module.exports = app;
